Fix ajax
backdrop-contrib/mosaic_grid pull request #13
Opened 2019-11-11 08:35 UTC by korontari

2019-11-11 18:52 UTC, klonos commented on README.md
> +- Captions that appear on mouse hover or static over the image bottom.
```suggestion
- Captions that appear over the image bottom, either statically, or on mouse hover.
```

2019-11-11 18:53 UTC, klonos commented on css/mosaic_grid.css
> +}
Please fix this.

2019-11-11 18:56 UTC, klonos commented on mosaic_grid.admin.inc
>      '#title' => t('Caption Font Color'),
We do not camel-case field labels.

```suggestion
    '#title' => t('Caption font color'),
```

2019-11-11 18:57 UTC, klonos commented on mosaic_grid.admin.inc
> +    '#title' => t('Caption Background Color'),
```suggestion
    '#title' => t('Caption background color'),
```

2019-11-11 18:59 UTC, klonos commented on mosaic_grid.admin.inc
> +    '#description' => t("Sets caption background color."),
Description/help text that basically repeats the field label is of no use, and it just overwhelms the UI. I would remove it (same on other fields too).

2019-11-11 18:59 UTC, klonos commented on mosaic_grid.admin.inc
>      '#title' => t('Caption Background Opacity'),
```suggestion
    '#title' => t('Caption background opacity'),
```

2019-11-11 19:02 UTC, klonos commented on mosaic_grid.admin.inc
> +    '#description' => t(
text within `t()` functions is not to be split when reaching 80 characters limit. Please put this in a single line. I would also remove the "Sets size of caption text" bit, since it just repeats the field label.

2019-11-11 19:04 UTC, klonos commented on mosaic_grid.admin.inc
>      '#title' => t('Caption Padding'),
```suggestion
   '#title' => t('Caption padding'),
```

2019-11-11 19:04 UTC, klonos commented on mosaic_grid.admin.inc
>      '#title' => t('Caption Font Size'),
```suggestion
    '#title' => t('Caption font size'),
```

2019-11-11 19:05 UTC, klonos commented on mosaic_grid.admin.inc
> +    '#description' => t(
Again, single line.

2019-11-11 19:06 UTC, klonos commented on mosaic_grid.admin.inc
> +      'Sets amount of background around caption text. Relative (<a href="@link" target="_blank">em</a>) units are used.
```suggestion
      'Sets the size of the space around the caption text. Relative (<a href="@link" target="_blank">em</a>) units are used.
```

2019-11-11 19:11 UTC, klonos commented on mosaic_grid.admin.inc
>      '#title' => t('Enable Lazy Loading'),
```suggestion
    '#title' => t('Enable lazy-loading'),
```

2019-11-11 19:13 UTC, klonos commented on mosaic_grid.admin.inc
>      '#description' => t("If enabled then images are loaded only when they get
```suggestion
    '#description' => t("Images are loaded only when they get within a visible page area. This considerably optimises the loading time of pages that contain many images. If you use some other module to lazy-load images on your site, then you may want to disable this option.
```

2019-11-11 19:15 UTC, klonos commented on mosaic_grid.admin.inc
> +
I know that this improves the readability here, but it is not allowed by our coding standards. Please remove extraneous spaces.

2019-11-11 19:15 UTC, klonos commented on mosaic_grid.info
> -version = 1.x-2.0.2
👍

2019-11-11 19:16 UTC, klonos commented on mosaic_grid.install
> +  // Check any views have their style plugin set to Mosaic Grid.
```suggestion
  // Check if any views have their style plugin set to Mosaic Grid.
```

2019-11-11 19:19 UTC, klonos commented on mosaic_grid.install
> +        $warnings[] = t(
Again, we do not split `t()` functions in multiple lines like that. It is not allowed by our coding standards.

2019-11-11 19:22 UTC, klonos commented on mosaic_grid.install
> +    $message .= '<ul><li>' . join('</li><li>', $warnings) . '</li></ul>';
Perhaps switch this to use [`theme_item_list()`](https://api.backdropcms.org/api/backdrop/1/search/theme_item_list), instead of creating the list "manually like so."

2019-11-11 19:22 UTC, klonos commented on mosaic_grid.install
> +}
Fix this please.

2019-11-11 19:23 UTC, klonos commented on mosaic_grid.module
> +      $views_theme_name   = config_get('views_ui.settings', 'custom_theme');
```suggestion
      $views_theme_name = config_get('views_ui.settings', 'custom_theme');
```

2019-11-11 19:24 UTC, klonos commented on mosaic_grid.module
> +        $views_human_name   = $themes[$views_theme_name  ]->info['name'];
```suggestion
        $views_human_name = $themes[$views_theme_name  ]->info['name'];
```

2019-11-11 19:28 UTC, klonos commented on mosaic_grid.module
> +      // Get width and height of an image.
```suggestion
      // Get width and height of an image. It is assumed that image field has
      // one value.
```

2019-11-11 19:29 UTC, klonos commented on mosaic_grid.module
>        // It is assumed that image field has one value.
...add this comment to the end of the previous one, in the same line.

2019-11-11 19:30 UTC, klonos commented on mosaic_grid.module
> +  // The rest of the function code below generates customized css
```suggestion
  // The rest of the function code below generates customized CSS, based on
```

2019-11-11 19:30 UTC, klonos commented on mosaic_grid.module
> +  // based on configuration and module options.
```suggestion
  // configuration, and module options.
```

2019-11-11 19:32 UTC, klonos commented on mosaic_grid.module
> +          $c = Color::hexToRgb($color_hex);
This variable name now seems "magic". Why change it from `$color`?

2019-11-11 19:33 UTC, klonos commented on mosaic_grid.module
> +      // Inrentionally no break here. Max-height is needed anyway.
```suggestion
      // Intentionally no break here. Max-height is needed anyway.
```

2019-11-11 19:34 UTC, klonos commented on mosaic_grid.module
> +    $c = Color::hexToRgb($bg_color);
Again, no "magic" variable names where possible.

2019-11-11 19:35 UTC, klonos commented on mosaic_grid.module
> +}
Fix this please.

2019-11-11 19:35 UTC, klonos commented on mosaic_grid.views.inc
> +}
...this too.

2019-11-11 19:36 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
Single spaces here please.

2019-11-11 19:37 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
>        '#title' => t('Maximum Row Height'),
```suggestion
      '#title' => t('Maximum row height'),
```

2019-11-11 19:37 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
>        '#description' => t('The maximum desired height of rows.'),
This help text is of no help; same as field label.

2019-11-11 19:38 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
>        '#field_suffix' => t('pix'),
```suggestion
      '#field_suffix' => t('px'),
```

2019-11-11 19:38 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      '#field_suffix' => t('pix'),
```suggestion
      '#field_suffix' => t('px'),
```

2019-11-11 19:40 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +        'Amount of space between items. To build a grid without gaps a value of <em>-1</em> is recommended.
```suggestion
        'Amount of space between items. To build a grid without gaps, a value of <em>-1</em> is recommended. This will prevent irregular gaps of one-pixel width.
```

2019-11-11 19:40 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      '#title' => t('Maximum Rows Number'),
```suggestion
      '#title' => t('Maximum rows number'),
```

2019-11-11 19:42 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      '#description' => t('Maximum number of rows to display. Items exceeding this
Again, single line:

```suggestion
      '#description' => t('Items exceeding this limit are hidden. Set to zero to display all rows.
```

2019-11-11 19:43 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      '#description' => t("Hide incomplete last row of items."),
```suggestion
      '#description' => t("Hide last row of items, if incomplete."),
```

2019-11-11 19:43 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      '#description' => t("If checked images with missing files are ignored."),
```suggestion
      '#description' => t("Ignore images with missing files."),
```

2019-11-11 19:44 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +    // Detect if text or title field is present and add it to the options list.
```suggestion
    // Detect if text or title field is present, and add it to the options list.
```

2019-11-11 19:44 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      '#title' => t('Text Source'),
```suggestion
      '#title' => t('Text source'),
```

2019-11-11 19:46 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      '#description' => t('Sets source for caption text. A text or title field
```suggestion
      '#description' => t('A text or title field can be added to the view, to be used as caption.'),
```

2019-11-11 19:47 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      'static' => t('Placed over image bottom'),
```suggestion
      'static' => t('Always visible, at the bottom of the image'),
```

2019-11-11 19:48 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      'hover'  => t('Appear on mouse hover'),
```suggestion
      'hover'  => t('Hidden initially; shown on mouse hover'),
```

2019-11-11 19:50 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      '#description' => t('Defines how captions should be displayed.'),
If you change the field title/label to something like "Caption display mode", you can get rid of this help text here 😉

2019-11-11 19:52 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +    // Title and description are made as markup elements.
Comments should wrap at 80 chars; no need to wrap separate sentences.

2019-11-11 19:53 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +    $caption_height = array(
Perhaps rename this variable to `$caption_height_options`?

2019-11-11 19:54 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      'fixed' => t('Set constant height'),
```suggestion
      'fixed' => t('Specific, fixed height'),
```

2019-11-11 19:54 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      'auto'  => t('Auto'),
```suggestion
      'auto'  => t('Automatic'),
```

2019-11-11 19:55 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      'limit' => t('Set height limit'),
```suggestion
      'limit' => t('Automatic, up to specific limit'),
```

2019-11-11 19:57 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      '#prefix' => '<div class="container-inline">',
Have you considered a container element, where you could place both the prefix and the suffix?

2019-11-11 19:58 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +        'Sets caption height. Units (<a href="@link" target="_blank">em</a>) are relative to capion font size.',
```suggestion
        'Sets caption height. Units (<a href="@link" target="_blank">em</a>) are relative to the font size of the caption.',
```

2019-11-11 20:02 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      '#description' => t('If checked caption text will be horisontally aligned with grid item.
Single line here. It would be great if we actually included the default padding here, instead of having the user visit the config page to see what that is:

```suggestion
      '#description' => t('Horizontally align the caption with the grid item. This overrides the padding setting in the <a href="@link" target="_blank">configuration page</a> (currently set to @global_padding_setting).',
```

2019-11-11 20:03 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      '#title' => t('No horisontal padding'),
```suggestion
      '#title' => t('No horizontal padding'),
```

2019-11-11 20:04 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
>        // If it is of required type return field handler and field name.
```suggestion
      // If it is of required type, return field handler and field name.
```

2019-11-11 20:05 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      // Title has no field_info so a second condition added.
```suggestion
      // Title has no field_info, so add a second condition.
```

2019-11-11 20:05 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +   * Returns first non excluded text field.
```suggestion
   * Returns first non-excluded text field.
```

2019-11-11 20:05 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +    //Do not validate when view is being created as there is no
```suggestion
    //Do not validate when view is being created, as there is no
```

2019-11-11 20:06 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
>      //image field by default and validation will fail.
```suggestion
    // image field by default, and validation will fail.
```

2019-11-11 20:07 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +      $is_title   = $field_name == 'title';
Single space here (and above please):

```suggestion
      $is_title = $field_name == 'title';
```

2019-11-11 20:07 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
> +        $errors[] = t('Invalid field types found. This format requires one image field and may optionally have one text or title field.');
```suggestion
        $errors[] = t('Invalid field types found. This format requires one image field, and may optionally have one text or title field.');
```

2019-11-11 20:08 UTC, klonos commented on views_plugin_style_mosaic_grid.inc
>        $errors[] = t('There are no image fields. This format requires one image field.');
```suggestion
      $errors[] = t('There are no image fields. This format requires at least one image field.');
```

2019-11-11 20:09 UTC, klonos requested changes
Please see my review comments.

2019-11-16 14:18 UTC, korontari commented on css/mosaic_grid.css
> +}
Fixed.

2019-11-16 14:25 UTC, korontari commented on mosaic_grid.admin.inc
> +    '#description' => t("Sets caption background color."),
Unnecessary descriptions removed.

2019-11-16 14:36 UTC, korontari commented on mosaic_grid.admin.inc
> +    '#description' => t(
If there is a second argument in t(), should I put it on the same line as well?

2019-11-16 14:50 UTC, korontari commented on mosaic_grid.admin.inc
> +
Done.

2019-11-16 16:37 UTC, korontari commented on views_plugin_style_mosaic_grid.inc
> +      '#prefix' => '<div class="container-inline">',
Good catch! I didn't know about container element. :) Thank you!

2019-11-16 16:52 UTC, korontari commented on views_plugin_style_mosaic_grid.inc
> +      '#description' => t('If checked caption text will be horisontally aligned with grid item.
Thank you for the advice! Very helpful!

2019-11-16 17:35 UTC, korontari commented on mosaic_grid.install
> +    $message .= '<ul><li>' . join('</li><li>', $warnings) . '</li></ul>';
Thank you for the advice! Reworked this.

2019-11-16 17:49 UTC, korontari commented
> Please see my review comments.

It looks like I have fixed all the requested changes (hopefully). I was inconsistent in commits. Some were made right from here, others by uploading edited files to the branch. Sorry, first time dealing with PR reviews. I wonder if you can see all the changes or should I create a fresh PR for that?

2020-01-28 09:44 UTC, merged